[theme]
# A Primary color (Teal from Logo)
primaryColor="#5B8A9E"  # Teal from logo

# A light, neutral background
backgroundColor="#FFF8F0" # Soft Cream

# A slightly darker sidebar/secondary background
secondaryBackgroundColor="#E6E6FA" # Lavender (soft purple)

# Text color (black for readability)
textColor="#191970" # Midnight Blue

# Font family (using a simple sans-serif that looks friendly)
font="sans serif"